//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Advent1 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Advent1.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7844
        ///1892
        ///10928
        ///4800
        ///9730
        ///3485
        ///7293
        ///
        ///11956
        ///2767
        ///12893
        ///2757
        ///3026
        ///9979
        ///
        ///4507
        ///4199
        ///2855
        ///1792
        ///2041
        ///4162
        ///3855
        ///2650
        ///2165
        ///5464
        ///2125
        ///4979
        ///4878
        ///6301
        ///
        ///2546
        ///3750
        ///1192
        ///4692
        ///6809
        ///2808
        ///6505
        ///2811
        ///6448
        ///4270
        ///2919
        ///1297
        ///1678
        ///
        ///2006
        ///6163
        ///5949
        ///2074
        ///5917
        ///5796
        ///3456
        ///1161
        ///6843
        ///3988
        ///4064
        ///5591
        ///
        ///17062
        ///14531
        ///5297
        ///
        ///16033
        ///18054
        ///25935
        ///
        ///3621
        ///3121
        ///5884
        ///5199
        ///4584
        ///4796
        ///1325
        ///3374
        ///5789
        ///2545
        ///5842
        ///1760
        ///5766
        ///1882
        ///3084
        ///
        ///10364
        ///1136
        ///2256
        ///5654
        ///7065
        ///5990
        ///3621
        ///8063
        ///        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Input {
            get {
                return ResourceManager.GetString("Input", resourceCulture);
            }
        }
    }
}
